# Asignaciones de pines para segmentos del display
set_property PACKAGE_PIN W7 [get_ports {AE}]
set_property IOSTANDARD LVCMOS33 [get_ports {AE}]
set_property PACKAGE_PIN W6 [get_ports {BE}]
set_property IOSTANDARD LVCMOS33 [get_ports {BE}]
set_property PACKAGE_PIN U8 [get_ports {CE}]
set_property IOSTANDARD LVCMOS33 [get_ports {CE}]
set_property PACKAGE_PIN V8 [get_ports {DE}]
set_property IOSTANDARD LVCMOS33 [get_ports {DE}]
set_property PACKAGE_PIN U5 [get_ports {EE}]
set_property IOSTANDARD LVCMOS33 [get_ports {EE}]
set_property PACKAGE_PIN V5 [get_ports {FE}]
set_property IOSTANDARD LVCMOS33 [get_ports {FE}]
set_property PACKAGE_PIN U7 [get_ports {GE}]
set_property IOSTANDARD LVCMOS33 [get_ports {GE}]

# Asignaciones de pines para selectores de display
set_property PACKAGE_PIN W4 [get_ports {select_disp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_disp[3]}]
set_property PACKAGE_PIN V4 [get_ports {select_disp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_disp[2]}]
set_property PACKAGE_PIN U4 [get_ports {select_disp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_disp[1]}]
set_property PACKAGE_PIN U2 [get_ports {select_disp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {select_disp[0]}]

# Asignación de pin para la señal de reloj principal
set_property PACKAGE_PIN W5 [get_ports {mclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {mclk}]

# Asignación de pines para señales de salida 'zero' y 'error'
set_property PACKAGE_PIN L1 [get_ports {zero}]
set_property IOSTANDARD LVCMOS33 [get_ports {zero}]
set_property PACKAGE_PIN P1 [get_ports {error}]
set_property IOSTANDARD LVCMOS33 [get_ports {error}]

# Asignación de pines para las entradas 'in1' y 'in2'
set_property PACKAGE_PIN R2 [get_ports {in1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in1[2]}]
set_property PACKAGE_PIN T1 [get_ports {in1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in1[1]}]
set_property PACKAGE_PIN U1 [get_ports {in1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in1[0]}]
set_property PACKAGE_PIN W2 [get_ports {in2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in2[2]}]
set_property PACKAGE_PIN R3 [get_ports {in2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in2[1]}]
set_property PACKAGE_PIN T2 [get_ports {in2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in2[0]}]

# Asignación de pines para la entrada de operación 'op'
set_property PACKAGE_PIN T3 [get_ports {op[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[1]}]
set_property PACKAGE_PIN V2 [get_ports {op[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[0]}]

# Asignación de pines para salida en decenas y unidades
set_property PACKAGE_PIN N3 [get_ports {dec_bin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dec_bin[3]}]
set_property PACKAGE_PIN P3 [get_ports {dec_bin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dec_bin[2]}]
set_property PACKAGE_PIN U3 [get_ports {dec_bin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dec_bin[1]}]
set_property PACKAGE_PIN W3 [get_ports {dec_bin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dec_bin[0]}]
set_property PACKAGE_PIN V3 [get_ports {unis_bin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {unis_bin[3]}]
set_property PACKAGE_PIN V13 [get_ports {unis_bin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {unis_bin[2]}]
set_property PACKAGE_PIN V14 [get_ports {unis_bin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {unis_bin[1]}]
set_property PACKAGE_PIN U14 [get_ports {unis_bin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {unis_bin[0]}]
